require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  Include:
    - 'app/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  Exclude:
    - 'db/schema.rb'
    - '**/*.js'
    - '**/*.jsx'
    - '**/*.tsx'
    - '**/*.d.ts'
    - '**/*.map'
    - '**/*.scss'
    - '**/*.css'
    - '**/*.key'
    - '**/*.yml'
    - '**/*.enc'
    - '**/*.erb'
    - '**/.keep'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - '**/.DS_Store'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Metrics/MethodLength:
  Max: 30

