require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  Include:
    - 'app/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  Exclude:
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - '**/*.erb'
    - '**/.keep'
    - '**/*.tsbuildinfo'
    - '**/.DS_Store'
    - '**/*.yml'
    - '**/*.enc'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Metrics/MethodLength:
  Max: 30

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

